## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf
from google.colab import files
#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop (columns= ['EIN'])
application_df. head (5)

,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Determine the number of unique values in each column.
for x in application_df.columns:
  print (x, len (application_df [x].unique ()))

NAME 19568
APPLICATION_TYPE 17
AFFILIATION 6
CLASSIFICATION 71
USE_CASE 5
ORGANIZATION 4
STATUS 2
INCOME_AMT 9
SPECIAL_CONSIDERATIONS 2
ASK_AMT 8747
IS_SUCCESSFUL 2

In [4]:
# Look at APPLICATION_TYPE value counts for binning
count= application_df ['NAME'].value_counts ()
count

PARENT BOOSTER USA INC                                                  1260
TOPS CLUB INC                                                            765
UNITED STATES BOWLING CONGRESS INC                                       700
WASHINGTON STATE UNIVERSITY                                              492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                          408
                                                                        ...
ST LOUIS SLAM WOMENS FOOTBALL                                              1
AIESEC ALUMNI IBEROAMERICA CORP                                            1
WEALLBLEEDRED ORG INC                                                      1
AMERICAN SOCIETY FOR STANDARDS IN MEDIUMSHIP & PSYCHICAL INVESTIGATI       1
WATERHOUSE CHARITABLE TR                                                   1
Name: NAME, Length: 19568, dtype: int64

In [6]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
names_replace = list (count[count<10].index)
#names_replace
# Replace in dataframe
for app in names_replace:
    application_df['NAME'] = application_df['NAME'].replace(app,"Other")

# Check to make sure binning was successful
application_df['NAME'].value_counts()

Other                                      21022
PARENT BOOSTER USA INC                      1260
TOPS CLUB INC                                765
UNITED STATES BOWLING CONGRESS INC           700
WASHINGTON STATE UNIVERSITY                  492
                                           ...
CASCADE 4-H FOUNDATION                        10
FREE & ACCEPTED MASONS OF WASHINGTON          10
NEW MEXICO GARDEN CLUBS INC                   10
NATIONAL ASSOCIATION OF HISPANIC NURSES       10
UNION OF CALIFORNIA STATE WORKERS             10
Name: NAME, Length: 223, dtype: int64

In [8]:
# Look at CLASSIFICATION value counts for binning
countbinning=application_df ['APPLICATION_TYPE'].value_counts ()
countbinning

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [9]:
# You may find it helpful to look at CLASSIFICATION value counts >1
application_df['APPLICATION_TYPE'].value_counts().loc [lambda x:x>1]

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
Name: APPLICATION_TYPE, dtype: int64

In [10]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list (countbinning [countbinning<300].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [11]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df=pd.get_dummies (application_df,dtype=float)
application_df.head ()

,STATUS,ASK_AMT,IS_SUCCESSFUL,NAME_ACE MENTOR PROGRAM OF AMERICA INC,NAME_AIR FORCE ASSOCIATION,NAME_ALABAMA FEDERATION OF WOMENS CLUBS,NAME_ALABAMA TREASURE FOREST ASSOCIATION,NAME_ALPHA PHI SIGMA,NAME_ALPHA PHI SIGMA INC,NAME_ALTRUSA INTERNATIONAL FOUNDATION INC,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [12]:
# Split our preprocessed data into our features and target arrays
y=application_df['IS_SUCCESSFUL'].values
X= application_df.drop ('IS_SUCCESSFUL', axis=1).values
# Split the preprocessed data into a training and testing dataset
X_train, X_test,y_train, y_test=train_test_split (X,y,random_state=0)
#change the types
#numeric_cols = application_df.select_dtypes(include=['float64']).columns
#categorical_cols = application_df.select_dtypes(include=['object']).columns

In [13]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [15]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE
number_input_features=len (X_train_scaled[0])
hidden_nodes_layer1=7
hidden_nodes_layer2=14
hidden_nodes_layer3=21

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense (units=hidden_nodes_layer1, input_dim=number_input_features,activation='relu'))

# Second hidden layer
nn.add(tf.keras.layers.Dense (units=hidden_nodes_layer2,activation='relu'))

# Output layer
nn.add (tf.keras.layers.Dense (units=1,activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 7)                 2324

 dense_4 (Dense)             (None, 14)                112

 dense_5 (Dense)             (None, 1)                 15

=================================================================
Total params: 2451 (9.57 KB)
Trainable params: 2451 (9.57 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [16]:
nn.compile (loss ='binary_crossentropy', optimizer ='adam',metrics=['accuracy'])

In [18]:
# Train the model
fit_model = nn.fit (X_train_scaled, y_train,validation_split =0.15,epochs =100)

Epoch 1/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4229 - accuracy: 0.7954 - val_loss: 0.4490 - val_accuracy: 0.7898
Epoch 2/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4226 - accuracy: 0.7955 - val_loss: 0.4500 - val_accuracy: 0.7893
Epoch 3/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4228 - accuracy: 0.7946 - val_loss: 0.4487 - val_accuracy: 0.7893
Epoch 4/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4232 - accuracy: 0.7958 - val_loss: 0.4486 - val_accuracy: 0.7888
Epoch 5/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4223 - accuracy: 0.7959 - val_loss: 0.4483 - val_accuracy: 0.7893
Epoch 6/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4230 - accuracy: 0.7940 - val_loss: 0.4477 - val_accuracy: 0.7909
Epoch 7/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4225 - accuracy: 0.7955 - val_loss: 0.4491 - val_accuracy: 0.7880
Epoch 8/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4229 - accuracy: 0.7958 - val_loss: 0.4488 - val_accuracy: 0.7875
Epoch 9/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4226 - accuracy: 0.7959 - val_loss: 0.4475 - val_accuracy: 0.7865
Epoch 10/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4227 - accuracy: 0.7954 - val_loss: 0.4472 - val_accuracy: 0.7898
Epoch 11/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4225 - accuracy: 0.7952 - val_loss: 0.4492 - val_accuracy: 0.7896
Epoch 12/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4224 - accuracy: 0.7956 - val_loss: 0.4499 - val_accuracy: 0.7885
Epoch 13/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4224 - accuracy: 0.7952 - val_loss: 0.4498 - val_accuracy: 0.7857
Epoch 14/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4226 - accuracy: 0.7965 - val_loss: 0.4467 - val_accuracy: 0.7891
Epoch 15/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4225 - accuracy: 0.7951 - val_loss: 0.4496 - val_accuracy: 0.7875
Epoch 16/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4218 - accuracy: 0.7962 - val_loss: 0.4489 - val_accuracy: 0.7880
Epoch 17/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4223 - accuracy: 0.7958 - val_loss: 0.4496 - val_accuracy: 0.7878
Epoch 18/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4222 - accuracy: 0.7950 - val_loss: 0.4474 - val_accuracy: 0.7875
Epoch 19/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4225 - accuracy: 0.7951 - val_loss: 0.4489 - val_accuracy: 0.7893
Epoch 20/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4225 - accuracy: 0.7952 - val_loss: 0.4495 - val_accuracy: 0.7854
Epoch 21/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4223 - accuracy: 0.7966 - val_loss: 0.4516 - val_accuracy: 0.7862
Epoch 22/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4223 - accuracy: 0.7947 - val_loss: 0.4526 - val_accuracy: 0.7870
Epoch 23/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4221 - accuracy: 0.7961 - val_loss: 0.4505 - val_accuracy: 0.7875
Epoch 24/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4219 - accuracy: 0.7954 - val_loss: 0.4515 - val_accuracy: 0.7875
Epoch 25/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4219 - accuracy: 0.7966 - val_loss: 0.4525 - val_accuracy: 0.7865
Epoch 26/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4217 - accuracy: 0.7954 - val_loss: 0.4536 - val_accuracy: 0.7875
Epoch 27/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4219 - accuracy: 0.7957 - val_loss: 0.4533 - val_accuracy: 0.7901
Epoch 28/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4221 - accuracy: 0.7951 - val_loss: 0.4543 - val_accuracy: 0.7888
Epoch 29/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4219 - accuracy: 0.7966 - val_loss: 0.4553 - val_accuracy: 0.7875
Epoch 30/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4217 - accuracy: 0.7953 - val_loss: 0.4544 - val_accuracy: 0.7885
Epoch 31/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4222 - accuracy: 0.7945 - val_loss: 0.4538 - val_accuracy: 0.7878
Epoch 32/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4217 - accuracy: 0.7954 - val_loss: 0.4563 - val_accuracy: 0.7860
Epoch 33/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4219 - accuracy: 0.7950 - val_loss: 0.4552 - val_accuracy: 0.7896
Epoch 34/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4218 - accuracy: 0.7962 - val_loss: 0.4550 - val_accuracy: 0.7885
Epoch 35/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4217 - accuracy: 0.7952 - val_loss: 0.4534 - val_accuracy: 0.7878
Epoch 36/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4218 - accuracy: 0.7952 - val_loss: 0.4558 - val_accuracy: 0.7885
Epoch 37/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4218 - accuracy: 0.7956 - val_loss: 0.4518 - val_accuracy: 0.7873
Epoch 38/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4217 - accuracy: 0.7958 - val_loss: 0.4534 - val_accuracy: 0.7875
Epoch 39/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4216 - accuracy: 0.7957 - val_loss: 0.4565 - val_accuracy: 0.7870
Epoch 40/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4217 - accuracy: 0.7956 - val_loss: 0.4552 - val_accuracy: 0.7865
Epoch 41/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4214 - accuracy: 0.7963 - val_loss: 0.4562 - val_accuracy: 0.7870
Epoch 42/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4217 - accuracy: 0.7962 - val_loss: 0.4541 - val_accuracy: 0.7862
Epoch 43/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4216 - accuracy: 0.7962 - val_loss: 0.4547 - val_accuracy: 0.7878
Epoch 44/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4218 - accuracy: 0.7959 - val_loss: 0.4548 - val_accuracy: 0.7875
Epoch 45/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4211 - accuracy: 0.7963 - val_loss: 0.4535 - val_accuracy: 0.7875
Epoch 46/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4218 - accuracy: 0.7965 - val_loss: 0.4553 - val_accuracy: 0.7873
Epoch 47/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4213 - accuracy: 0.7962 - val_loss: 0.4545 - val_accuracy: 0.7875
Epoch 48/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4211 - accuracy: 0.7961 - val_loss: 0.4602 - val_accuracy: 0.7891
Epoch 49/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4211 - accuracy: 0.7957 - val_loss: 0.4559 - val_accuracy: 0.7867
Epoch 50/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4214 - accuracy: 0.7962 - val_loss: 0.4569 - val_accuracy: 0.7870
Epoch 51/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4212 - accuracy: 0.7965 - val_loss: 0.4545 - val_accuracy: 0.7878
Epoch 52/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4214 - accuracy: 0.7952 - val_loss: 0.4565 - val_accuracy: 0.7875
Epoch 53/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4210 - accuracy: 0.7963 - val_loss: 0.4558 - val_accuracy: 0.7878
Epoch 54/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4210 - accuracy: 0.7964 - val_loss: 0.4600 - val_accuracy: 0.7852
Epoch 55/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4211 - accuracy: 0.7968 - val_loss: 0.4596 - val_accuracy: 0.7867
Epoch 56/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4211 - accuracy: 0.7962 - val_loss: 0.4615 - val_accuracy: 0.7839
Epoch 57/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4210 - accuracy: 0.7971 - val_loss: 0.4605 - val_accuracy: 0.7888
Epoch 58/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4210 - accuracy: 0.7967 - val_loss: 0.4615 - val_accuracy: 0.7878
Epoch 59/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4212 - accuracy: 0.7956 - val_loss: 0.4640 - val_accuracy: 0.7870
Epoch 60/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4206 - accuracy: 0.7972 - val_loss: 0.4645 - val_accuracy: 0.7862
Epoch 61/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4209 - accuracy: 0.7959 - val_loss: 0.4629 - val_accuracy: 0.7847
Epoch 62/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4208 - accuracy: 0.7956 - val_loss: 0.4629 - val_accuracy: 0.7852
Epoch 63/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4208 - accuracy: 0.7958 - val_loss: 0.4649 - val_accuracy: 0.7862
Epoch 64/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4209 - accuracy: 0.7962 - val_loss: 0.4620 - val_accuracy: 0.7885
Epoch 65/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4204 - accuracy: 0.7961 - val_loss: 0.4622 - val_accuracy: 0.7880
Epoch 66/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4208 - accuracy: 0.7965 - val_loss: 0.4634 - val_accuracy: 0.7880
Epoch 67/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4210 - accuracy: 0.7957 - val_loss: 0.4610 - val_accuracy: 0.7880
Epoch 68/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4208 - accuracy: 0.7966 - val_loss: 0.4637 - val_accuracy: 0.7873
Epoch 69/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4210 - accuracy: 0.7966 - val_loss: 0.4613 - val_accuracy: 0.7891
Epoch 70/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4212 - accuracy: 0.7967 - val_loss: 0.4626 - val_accuracy: 0.7891
Epoch 71/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4209 - accuracy: 0.7959 - val_loss: 0.4665 - val_accuracy: 0.7878
Epoch 72/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4208 - accuracy: 0.7953 - val_loss: 0.4628 - val_accuracy: 0.7883
Epoch 73/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4206 - accuracy: 0.7956 - val_loss: 0.4661 - val_accuracy: 0.7885
Epoch 74/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4205 - accuracy: 0.7966 - val_loss: 0.4646 - val_accuracy: 0.7873
Epoch 75/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4207 - accuracy: 0.7955 - val_loss: 0.4659 - val_accuracy: 0.7862
Epoch 76/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4208 - accuracy: 0.7968 - val_loss: 0.4616 - val_accuracy: 0.7870
Epoch 77/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4208 - accuracy: 0.7957 - val_loss: 0.4622 - val_accuracy: 0.7873
Epoch 78/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4207 - accuracy: 0.7969 - val_loss: 0.4652 - val_accuracy: 0.7885
Epoch 79/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4207 - accuracy: 0.7975 - val_loss: 0.4666 - val_accuracy: 0.7893
Epoch 80/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4210 - accuracy: 0.7957 - val_loss: 0.4654 - val_accuracy: 0.7888
Epoch 81/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4202 - accuracy: 0.7964 - val_loss: 0.4678 - val_accuracy: 0.7896
Epoch 82/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4203 - accuracy: 0.7962 - val_loss: 0.4709 - val_accuracy: 0.7888
Epoch 83/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4207 - accuracy: 0.7962 - val_loss: 0.4661 - val_accuracy: 0.7885
Epoch 84/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4205 - accuracy: 0.7964 - val_loss: 0.4650 - val_accuracy: 0.7867
Epoch 85/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4206 - accuracy: 0.7966 - val_loss: 0.4664 - val_accuracy: 0.7885
Epoch 86/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4203 - accuracy: 0.7963 - val_loss: 0.4684 - val_accuracy: 0.7891
Epoch 87/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4206 - accuracy: 0.7952 - val_loss: 0.4668 - val_accuracy: 0.7888
Epoch 88/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4207 - accuracy: 0.7966 - val_loss: 0.4669 - val_accuracy: 0.7880
Epoch 89/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4206 - accuracy: 0.7962 - val_loss: 0.4667 - val_accuracy: 0.7893
Epoch 90/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4202 - accuracy: 0.7960 - val_loss: 0.4640 - val_accuracy: 0.7891
Epoch 91/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4207 - accuracy: 0.7960 - val_loss: 0.4664 - val_accuracy: 0.7883
Epoch 92/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4205 - accuracy: 0.7957 - val_loss: 0.4682 - val_accuracy: 0.7875
Epoch 93/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4206 - accuracy: 0.7969 - val_loss: 0.4682 - val_accuracy: 0.7885
Epoch 94/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4207 - accuracy: 0.7965 - val_loss: 0.4669 - val_accuracy: 0.7880
Epoch 95/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4205 - accuracy: 0.7971 - val_loss: 0.4675 - val_accuracy: 0.7852
Epoch 96/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4205 - accuracy: 0.7957 - val_loss: 0.4694 - val_accuracy: 0.7862
Epoch 97/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4208 - accuracy: 0.7963 - val_loss: 0.4694 - val_accuracy: 0.7893
Epoch 98/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4206 - accuracy: 0.7962 - val_loss: 0.4682 - val_accuracy: 0.7878
Epoch 99/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4204 - accuracy: 0.7956 - val_loss: 0.4710 - val_accuracy: 0.7901
Epoch 100/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4201 - accuracy: 0.7962 - val_loss: 0.4760 - val_accuracy: 0.7893

In [19]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.4805 - accuracy: 0.7773 - 335ms/epoch - 1ms/step
Loss: 0.48050156235694885, Accuracy: 0.7772594690322876

In [20]:
# Export our model to HDF5 file
nn.save ('/boot/Model_3.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3079: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [21]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
from google.colab import drive
drive.mount('/boot/drive')

Drive already mounted at /boot/drive; to attempt to forcibly remount, call drive.mount("/boot/drive", force_remount=True).